### ISSUE TITLE
Logo (grüne Leiste)

### ISSUE THREAD

**Issue by eknoes** [errotu/digital-vernissage#3]
Alternativ zu einer grünen Leiste könnte das WeeDooCare-Logo (mit Schriftzug) vor dem DigitalVernissage stehen.

**Comment by eknoes** [comment]
@errotu Wie meinst du das, welche grüne Leiste?

**Comment by errotu** [comment]
Im Issue #2 wird auch angesprochen, dass die Farbe der Leiste grün werden sollte. Favorisiert ist jetzt aber eher, dass sie weiß bleibt und davor das [WeeDooCare-Logo ](http://weedoocare.com/images/WeeDooCare_Logo.png)kommt.

**Comment by eknoes** [comment]
Also dass im Titel Quasi "WeeDooCare-Logo" Vernissage steht?

**Comment by errotu** [comment]
Genau

**Comment by eknoes** [comment]
Das WeeDooCare-Logo ist zu groß. WeeDooCare als Text mit Vernissage ist auch zu lang. Mein aktueller Vorschlag wäre "Digital [Cloud-Icon] Vernissage". Ist in der aktuellen Version so eingebaut, was denkst du?

**Comment by errotu** [comment]
Dann besser nicht das Cloud-Logo, sondern das reine WeeDooCare-Logo. Hast eine Mail mit Logo bekommen.

**Comment by eknoes** [comment]
Also soll kein Digital Vernissage mehr auftauchen im Titel?

**Comment by errotu** [comment]
Nein, sondern: "Digital [WeeDooCare-Icon] Vernissage"

**Comment by eknoes** [comment]
Ist jetzt so implementiert, allerdings nur für iOS, weil es auf Android nicht passt da die Titelleiste ja auch grün ist.
