### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by eknoes** [errotu/digital-vernissage#4]
Logo muss überarbeitet werden. Damit das WeeDooCare-Logo besser sichtbar ist, sollte die Cloud entfernt werden und das Symbol der App nur noch das Logo sein. Damit es sich nicht mit dem Grün beißt, einfach mit ein weißen Hintergrund, ähnlich wie bei der Dropbox App.

**Comment by eknoes** [comment]
@errotu Hast du Lust, das zu erledigen? [Hier](http://pgicons.abiro.com/) kannst du dir dann die ganzen einzelnen Dateien generieren lassen!

**Comment by errotu** [comment]
Ja, das übernehme ich.

**Comment by errotu** [comment]
Neue Ordner liegen nun im Ordner res, sind aber anscheinend in der neuen kompilierten Fassung noch nicht ausgetauscht. Müssen sie noch in andere Ordner verschoben werden?

**Comment by eknoes** [comment]
Wie neue Ordner? Die neuen Logos wurden doch ersetzt. Soll das Logo auch keine abgerundeten Ecken mehr haben oder sowas, wirklich nur der Kasten?

**Comment by errotu** [comment]
Das ist ja mein Punkt. Habe die Logos im res-Ordner ersetzt, das Logo der App hat sich aber nicht verändert. Irgendwas fehlt offensichtlich also noch...
Ich probiere bei den Logos mal ein bisschen rum. Hast du die abgerundeten Ecken und sowas damit selbst erstellt?

**Comment by eknoes** [comment]
Ja genau, das geht mit Android Studio. Soll ich das mit dem neuen Logo machen, das transparent auf ein weißes, abgerundetes "Grundicon"?

**Comment by errotu** [comment]
Bei einem weißen abgerundeten "GrundIcon", kannst du einfach das transparente WeeDooCare-Logo aus dem Logo-Ordner, den ich dir geteilt habe, nehmen. Ansonsten hört sich das sehr gut!

**Comment by eknoes** [comment]
Ist mit 30e0a5c2c172131e6b1b956ffad88a1663992368 gefixed!
