### ISSUE TITLE
UI Flow

### ISSUE THREAD

**Issue by eknoes** [errotu/digital-vernissage#6]
In der Einzelbild-Ansicht: Bisher ist es nicht intuitiv genug. Es muss einen Hinweis geben, damit man das Bild anklickt. "More Details" oder ein Anreißer zum Text, der dann hinter dem Bild liegt. Ähnlich wie bei der Desktop-Version von EcotopianDreams.

**Comment by errotu** [comment]
[Hier noch der Link zu EcotopianDreams](http://ecotopiandreams.com/)

**Comment by eknoes** [comment]
Ich stelle mir beim ersten Aufruf ein (Popover)[https://onsen.io/v2/docs/react/Popover.html] vor, dass einem das anzeigt?

**Comment by eknoes** [comment]
Das Popover sah nicht gut aus, ich denke das Modal ist eine bessere Variante. Es wird nur einmalig angezeigt!
